import Axios from 'axios';
import NavAdmin from '@/components/NavAdmin';
import ProfessionalAction from '@/components/ProfessionalAction';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import MenuProfessionals from '@/components/MenuProfessionals'; 

export default function professionals() {
  const API_URL = "http://localhost:8080/api/professionals";

  const [professional, setProfessional] = useState([]);

  useEffect(() => {
    const getAllProfessionals = async () => {
      try {
        const response = await Axios.get(API_URL);
        setProfessional(response.data);
      } catch (error) {
        console.error('Erro ao buscar os profissionais:', error);
      }
    };

    getAllProfessionals();
  }, []);

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuProfessionals />
      </div>

      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
            <h3> Lista de Profissionais </h3>

            <table className="table table-hover">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nome</th>
                  <th scope="col">E-mail</th>
                  <th scope="col">Ação</th>
                </tr>
              </thead>
              <tbody>
  {Array.isArray(professionals) && professionals.length > 0 ? (
    professionals.map(professional => (
      <tr key={professional._id}>
        <th scope="row">{professional._id}</th>
        <td>{professional.name}</td>
        <td>{professional.email}</td>
        <td>{professional.specialty}</td>
      </tr>
    ))
  ) : (
    <tr>
    </tr>
  )}
</tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  );
}
