import Axios from 'axios';
import NavAdmin from '@/components/NavAdmin';
import ProfessionalAction from '@/components/ProfessionalAction';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import MenuProfessionals from '@/components/MenuProfessionals'; 

export default function professionals() {
  const API_URL = "http://localhost:3030/api/professionals";

  const [professionals, setProfessionals] = useState([]);

  useEffect(() => {
    const getAllProfessionals = async () => {
      try {
        const response = await Axios.get(API_URL);
        setProfessionals(response.data);
      } catch (error) {
        console.error('Erro ao buscar os profissionais:', error);
      }
    };

    getAllProfessionals();
  }, []);

  return (
    <>
      <Head>
        <title>Profissionais</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuProfessionals />
      </div>

      <div>
        <div className="container">
          <div className="row border-bottom">
            <h3> Lista de Profissionais </h3>

            <table className="table table-hover">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nome</th>
                  <th scope="col">E-mail</th>
                  <th scope="col">Ação</th>
                </tr>
              </thead>
              <tbody>

              {professionals.map( professional => (
            <tr key={professional._id}>
              <th scope="row">{professional._id}</th>
              <td>{professional.professional_name}</td>
              <td>{professional.professional_email}</td>
              <td>
                <ProfessionalAction pid={ professional._id }></ProfessionalAction>
              </td>
            </tr>
        ))}

  {/* {Array.isArray(professionals) && professionals.length > 0 ? (
    professionals.map(professional => (
      <tr key={professional._id}>
        <th scope="row">{professional._id}</th>
        <td>{professional.professional_name}</td>
        <td>{professional.professional_email}</td>
        <td>{professional.professional_specialty}</td>
      </tr>
    ))
  ) : (
    <tr>
    </tr>
  )} */}
</tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  );
}