// import MenuAdmin from '@/components/MenuAdmin'
// import NavAdmin from '@/components/NavAdmin'
// import Head from 'next/head'
// import Link from 'next/link'

// export default function admin() {
//   return (
//     <>
//       <Head>
//         <title>APP-BC</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//       </Head>
//       <div>
//         <NavAdmin />
//         <MenuAdmin />
//       </div>
//       <div>
//         <h3>HOME</h3>
//       </div>
//   </>
//   )
// }
import MenuAdmin from '@/components/MenuAdmin'
import NavAdmin from '@/components/NavAdmin'
import Head from 'next/head'
import Link from 'next/link'

export default function admin() {
  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuAdmin />
      </div>
      <div id="home-content">
        <h3 id="home-title">Bem-vindo à Área Administrativa</h3>
        <div id="pages-info">
          <section id="usuarios-info">
            <h4>Usuários</h4>
            <p>Gerencie os usuários registrados, incluindo a criação, edição e exclusão de contas.</p>
            <Link href="/admin/users">Ver Usuários</Link>
          </section>
          <section id="agendamentos-info">
            <h4>Agendamentos</h4>
            <p>Visualize e gerencie os agendamentos realizados pelos usuários e profissionais.</p>
            <Link href="/admin/appointments">Ver Agendamentos</Link>
          </section>
          <section id="professores-info">
            <h4>Professores</h4>
            <p>Controle o cadastro e os dados dos professores envolvidos nos eventos e atividades.</p>
            <Link href="/admin/teachers">Ver Professores</Link>
          </section>
          <section id="profissionais-info">
            <h4>Profissionais</h4>
            <p>Gerencie os dados e a atuação dos profissionais da plataforma.</p>
            <Link href="/admin/professionals">Ver Profissionais</Link>
          </section>
          <section id="estudantes-info">
            <h4>Estudantes</h4>
            <p>Administre os registros dos estudantes que participam das atividades e eventos.</p>
            <Link href="/admin/students">Ver Estudantes</Link>
          </section>
          <section id="eventos-info">
            <h4>Eventos</h4>
            <p>Gerencie os eventos realizados na plataforma, incluindo criação, edição e visualização.</p>
            <Link href="/admin/events">Ver Eventos</Link>
          </section>
        </div>
      </div>
    </>
  )
}



