import MenuAdmin from '@/components/MenuAdmin'
import NavAdmin from '@/components/NavAdmin'
import Head from 'next/head'
import Link from 'next/link'

export default function admin() {
  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuAdmin />
      </div>
      <div>
        <h3>HOME</h3>
      </div>
  </>
  )
}


