import Axios from 'axios'
import NavAdmin from '@/components/NavAdmin'
import EventAction from '@/components/EventAction'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import MenuEvents from '@/components/MenuEvents'


export default function events() {

  const API_URL = "http://localhost:3030/api/events"
  
  const [events, setEvents] = useState([]); 
  
  useEffect(() => {
    const getAllEvents = async () => {
      try {
        const response = await Axios.get(API_URL);
        setEvents(response.data);
      } catch (error) {
        console.error('Erro ao buscar os eventos:', error);
      }
    };

    getAllEvents();

  }, []);

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuEvents />
      </div>

  
      <div>
        <div className="container">
        <div className="row border-bottom">
        <h3> Lista de Eventos </h3>
        
        <table className="table table-hover">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Título</th>
            <th scope="col">Descrição</th>
            <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>

        {events.map( event => (
            <tr key={event._id}>
              <th scope="row">{event._id}</th>
              <td>{event.event_title}</td>
              <td>{event.event_description}</td>
              <td>
                <EventAction pid={ event._id }></EventAction>
              </td>
            </tr>
        ))}

        </tbody>
        </table>
        </div>
        </div>
      </div>  
  </>
  )
}


